name: Update IP Lists
on:
  schedule:
    - cron: '0 0 * * *' # اجرای خودکار هر روز ساعت ۰۰:۰۰
  workflow_dispatch: # اجازه اجرای دستی از پنل گیت‌هاب

jobs:
  update-ips:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install jq
        run: sudo apt-get install -y jq

      - name: Run script and generate files
        run: |
          chmod +x get.sh  # نام اسکریپت خود را اینجا بنویسید
          ./get.sh v4 > ir_ips_v4.rsc
          ./get.sh v6 > ir_ips_v6.rsc

      - name: Commit and push changes
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
          git add ir_ips_v4.rsc ir_ips_v6.rsc
          git diff --quiet && git diff --staged --quiet || (git commit -m "Update IP lists - $(date)" && git push)
